name: Deploy NextJS to Azure App Services

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_NAME: get-local-frontend # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '12.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy-production:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.SCM_CREDENTIALS }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  build-and-deploy-development:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'get-local-frontend-Development'
          publish-profile: ${{ secrets.SCM_CREDENTIALS }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
